{{- if .Values.redis.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "distributed-crawler.name" . }}-redis
  labels:
    {{- include "distributed-crawler.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "distributed-crawler.name" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "distributed-crawler.name" . }}-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image }}"
          ports:
            - containerPort: {{ .Values.redis.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "distributed-crawler.name" . }}-redis
  labels:
    {{- include "distributed-crawler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
  selector:
    app: {{ include "distributed-crawler.name" . }}-redis
{{- end }}
